game.splash("welcome to phobia:", "the game")
game.splash("by phobia inc")
game.splash("employees of phobia", "OWNERS: Timothy and miles")
game.splash("worker:sayori", "high arms:matthew")
game.splash("coder:Elijah", "coder:Caleb")
game.splash("CO-OWNER:Torrance", "WORKER:Zayden")
game.splash("CHAIRMAN:Joile", "Employee:lance")
game.splash("enjoy the game!")
textSprite = textsprite.create("Phobia")
textSprite.set_position(75, 21)
textSprite.set_max_font_height(11)
textSprite2 = textsprite.create("The game")
textSprite2.set_position(75, 35)
textSprite3 = textsprite.create("Play")
textSprite3.set_position(75, 65)
textSprite3.set_max_font_height(11)
textSprite4 = textsprite.create("Achievements ")
textSprite4.set_position(56, 86)
textSprite4.set_max_font_height(11)
textSprite5 = textsprite.create("Settings")
textSprite5.set_position(59, 114)
textSprite5.set_max_font_height(11)